# Generated by Django 5.0 on 2024-01-07 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0003_selecciondiaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprador',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
