# Generated by Django 5.0 on 2024-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0005_alter_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
