# Generated by Django 5.0 on 2024-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='grupo',
            field=models.CharField(choices=[('postres', 'Postres'), ('comida_rapida', 'Comida rápida'), ('dulces', 'Dulces'), ('ensaladas', 'Ensaladas'), ('desayunos', 'Desayunos'), ('antojitos', 'Antojitos')], default='Postres', max_length=15),
        ),
    ]
