# Generated by Django 5.0 on 2024-01-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0008_producto_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='grupo',
            field=models.CharField(choices=[('postres', 'Postres'), ('comida_rapida', 'Comida rápida'), ('dulces', 'Dulces'), ('ensaladas', 'Ensaladas'), ('desayunos', 'Desayunos'), ('antojitos', 'Antojitos')], default='postres', max_length=15),
        ),
    ]
