# Generated by Django 5.0 on 2024-01-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0009_alter_producto_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
