# Generated by Django 5.0 on 2024-01-08 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0010_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
