# Generated by Django 5.2.7 on 2025-10-27 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPIICSA_STORE', '0011_alter_usuario_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
